### ISSUE TITLE
Config for example4 different than README

### ISSUE THREAD

**Issue by bsiranosian** [seqeralabs/wave-showcase#1]
The README for example4 specifies `strategy = 'conda,container'`

But the actual config file just specifies 'conda': https://github.com/seqeralabs/wave-showcase/blob/master/example4/nextflow.config#L7

From the output, it's not clear if/where the container is being built in either case.

**Comment by pditommaso** [comment]
Well spotted. If you specify `strategy = 'conda'` Wave strictly requires the use of a `conda` directive to build the container. Instead using `strategy = 'conda,container'` it looks for `conda` first and fallback to the process `container`. 

To check the actually container used you can run the command

```
nextflow log last -f name,container
```

**Comment by pditommaso** [comment]
Thanks for reporting this. Solved by 538056ca
